name: Deploy to Server

# Trigger this workflow when the build workflow completes successfully
on:
  workflow_run:
    workflows: ['Build and Push Docker Image']
    types:
      - completed

jobs:
  # Deploy the application to the production server
  deploy:
    # Only run if the build workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Connect to the server and deploy the new Docker container
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          # SSH connection details (configured in repository secrets)
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Deployment script
          script: |
            set -e  # Exit the script if any command fails

            # Step 1: Log in to GitHub Container Registry
            echo "🔄 Connecting to the server..."
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Step 2: Pull the latest Docker image
            echo "📥 Pulling the latest Docker image..."
            docker pull ghcr.io/${{ github.repository_owner }}/frizbee:latest

            # Step 3: Stop and remove the existing container
            echo "🛑 Stopping and removing the existing container..."
            docker stop frizbee || true
            docker rm frizbee || true

            # Step 4: Start a new container with the latest image
            echo "🚀 Starting the new container..."
            docker run -d \
              --name frizbee \
              --restart unless-stopped \
              -p 3002:3000 \
              --env-file ~/frizbee/.env \
              ghcr.io/${{ github.repository_owner }}/frizbee:latest

            # Step 5: Connect the container to the Docker network
            echo "🔗 Connecting the container to the network..."
            docker network connect frizbee_webnet frizbee

            echo "✅ Deployment completed successfully!"
